version: "2"
services:
  ms-config:
    image: openjdk:8-jdk-alpine
    container_name: ms-config
    volumes:
      - ../../ms-config/src/main/docker:/usr/local/share/hml
    ports:
      - "8888:8888"
    entrypoint: /usr/local/share/hml/run.sh
  ms-core:
    image: openjdk:8-jdk-alpine
    depends_on:
      - ms-config
    container_name: ms-core
    links:
      - ms-config:ms-config
    volumes:
      - ../../ms-core/src/main/docker:/usr/local/share/hml
    ports:
      - "8080:8080"
    entrypoint: /usr/local/share/hml/run.sh
    environment:
      PROFILE: "default"
      CONFIGSERVER_URI: "http://ms-config:8888"
      CONFIGSERVER_PORT:   "8888"
