version: "2"
services:
  active-mq:
    image: webcenter/activemq:latest
    container_name: active-mq
    ports:
      - "8161:8161"
      - "61616:61616"
      - "5672:5672"
      - "61613:61613"
      - "1883:1883"
      - "61614:61614"
  ms-config:
    image: openjdk:8-jdk-alpine
    container_name: ms-config
    volumes:
      - ../../ms-config/src/main/docker:/usr/local/share/hml
    ports:
      - "8888:8888"
    entrypoint: /usr/local/share/hml/run.sh
    environment:
      BROKER_PORT:  "61616"
  ms-core:
    image: openjdk:8-jdk-alpine
    depends_on:
      - ms-config
    container_name: ms-core
    links:
      - ms-config:ms-config
      - active-mq:active-mq
    volumes:
      - ../../ms-core/src/main/docker:/usr/local/share/hml
    ports:
      - "8080:8080"
    entrypoint: /usr/local/share/hml/run.sh
    environment:
      PROFILE: "default"
      CONFIGSERVER_URI: "http://ms-config:8888"
      CONFIGSERVER_PORT:   "8888"
      BROKER_PORT:  "61616"