server:
  port: 8888
spring:
  cloud:
    config:
      server:
        encrypt.enabled: false
        git:
          uri: https://github.com/nicolasduminil/spring-config
          searchPaths: hml-core
          username: nicolasduminil
          password: California1
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    fr.simplex_software.micro_services.config: DEBUG